spring:
  application:
    name: 301javamicro
  datasource:
    driverClassName: org.h2.Driver
    password: pass
    url: jdbc:h2:mem:testdb
    username: pass

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

server:
  port: 8080


security:
  oauth2:
    client:
      access-token-uri: https://dev-912784.okta.com/oauth2/default/v1/token
      client-id: '0oaibgrorRm5bxLZD4x6'
      client-secret: 'sSjWC_KKTCP3kRBHJUdlWGMWA08MkvvjDWEU9S7T'
      scope: openid profile email
      user-authorization-uri: https://dev-912784.okta.com/oauth2/default/v1/authorize
    resource:
      user-info-uri: https://dev-912784.okta.com/oauth2/default/v1/userinfo

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings